#!/bin/bash
# /etc/init.d/tankmonitor

### BEGIN INIT INFO
# Provides:          tankmonitor
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Tankmonitor
# Description:       This service is used to start and stop the Thunderbird Creek tank monitor
### END INIT INFO

case "$1" in
    start)
        echo "Starting tankmonitor"
        /home/pi/tankmonitor/start
        ;;
    stop)
        echo "Stopping tankmonitor"
        killall tankmonitor
        ;;
    *)
        echo "Usage: /etc/init.d/tankmonitor start|stop"
        exit 1
        ;;
esac

exit 0